[project]
name = "2602-staticencrypt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cryptography>=46.0.5",
    "markdown>=3.10.2",
]
